### ISSUE TITLE
Crash on [self.context presentRenderbuffer:GL_RENDERBUFFER];

### ISSUE THREAD

**Issue by arpitjain03** [nickypatson/LiveYoutubeBoardCasting#1]
Getting crash on line 214 GPUImageContext.m file in - (void)presentBufferForDisplay;
function.
Tried pod update and install

**Comment by nickypatson** [comment]
This issue is in iOS 11 right, this has to be fix by **LFLiveKit**
Alternative solution will be 

**product -> scheme -> Edit scheme**
choose **options** tab and there you find an option **CPU Frame Capture** set **Disable**

Hope this works. Now enjoy!
I am closing this issue tracker
